Closes#207 Implemented publish/unpublish fro decks
koldovsky/orlp-web pull request #208
Opened 2018-10-31 16:51 UTC by OlehPaliuh

2018-10-31 18:54 UTC, maxturko reviewed
I was not able to figure out how to publish/unpublish decks on the website, where exactly is the button located?

2018-11-01 05:57 UTC, OlehPaliuh commented
@maxturko In the cabinet, you can see subscribed decks and if you are the owner of the deck, there will be "PUBLIC" or "PRIVATE" button after "Start" button. Also, you can visit "Manege decks", after that chose some deck and on the right side of the screen you will see "PRIVATE" or "PUBLIC" button.

2018-11-01 06:38 UTC, antonbakalets commented on src/app/page/cabinet/cabinet.component.html
> +        <td *ngIf="!isOwnerDeck(deck)"></td>
Twice the same expression. is it a typo?

2018-11-01 06:38 UTC, antonbakalets commented on src/app/page/cabinet/cabinet.component.ts
> +      .subscribe((response) => console.log());
Use the fact
`import {NGXLogger} from 'ngx-logger';`
istead of 
`console.log()`

2018-11-01 06:38 UTC, antonbakalets commented on src/app/page/cabinet/cabinet.service.ts
> +      .map((response: Response) => this.logger.log(response));
Here the logger is used correctly.

2018-11-01 06:38 UTC, antonbakalets commented on src/app/page/cabinet/userDecks/user.decks.component.html
> +              (click)="changeAccessDeck(selectedDeck, false)">PRIVATE</button>
i'm not sure if UPPERCASE is acceptable in user messages.

2018-11-01 11:24 UTC, OlehPaliuh commented on src/app/page/cabinet/cabinet.component.html
> +        <td *ngIf="!isOwnerDeck(deck)"></td>
Thanks, I corrected this mistake

2018-11-01 11:26 UTC, OlehPaliuh commented on src/app/page/cabinet/userDecks/user.decks.component.html
> +              (click)="changeAccessDeck(selectedDeck, false)">PRIVATE</button>
In this case, I agree with you, so I corrected to lowercase.

2018-11-01 11:28 UTC, OlehPaliuh commented on src/app/page/cabinet/cabinet.component.ts
> +      .subscribe((response) => console.log());
Tanks, I changed that.

2018-11-01 20:49 UTC, antonbakalets approved these changes

2018-11-02 01:24 UTC, maxturko requested changes

2018-11-02 01:24 UTC, maxturko commented on src/app/page/cabinet/userDecks/user.decks.component.ts
> +              private deckService: DeckService) {
Your version is not building successfully

The errors I get are:
ERROR in D:/Project/orlp-web/src/app/page/cabinet/userDecks/user.decks.component.ts (118,37): Property 'logger' does not exist on type 'UserDecksComponent'.
ERROR in D:/Project/orlp-web/src/app/page/cabinet/userDecks/user.decks.component.ts (118,37): Property 'logger' does not exist on type 'UserDecksComponent'.

webpack: Failed to compile.

I suggest adding "private logger: NGXLogger" to this constructor and replacing line 12 with: "import {NGXLogger} from 'ngx-logger';"

2018-11-02 06:09 UTC, OlehPaliuh commented on src/app/page/cabinet/userDecks/user.decks.component.ts
> +              private deckService: DeckService) {
Thanks, I corrected that.

2018-11-02 08:35 UTC, Maks-Chornyi approved these changes

2018-11-02 08:39 UTC, OleksandrBartosh approved these changes

2018-11-02 10:25 UTC, maxturko approved these changes

2018-11-02 10:32 UTC, merged